export const initialNotifications = [
    {
      id: 1,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "Chris Tompson",
      action: "requested review on",
      target: "PR #42: Feature implementation",
      timestamp: "15 minutes ago",
      unread: true,
    },
    {
      id: 2,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "Emma Davis",
      action: "shared",
      target: "New component library",
      timestamp: "45 minutes ago",
      unread: true,
    },
    {
      id: 3,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "James Wilson",
      action: "assigned you to",
      target: "API integration task",
      timestamp: "4 hours ago",
      unread: false,
    },
    {
      id: 4,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "Alex Morgan",
      action: "replied to your comment in",
      target: "Authentication flow",
      timestamp: "12 hours ago",
      unread: false,
    },
    {
      id: 5,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "Sarah Chen",
      action: "commented on",
      target: "Dashboard redesign",
      timestamp: "2 days ago",
      unread: false,
    },
    {
      id: 6,
      image: "https://i.pinimg.com/736x/b6/de/1f/b6de1f1d0413558c51eac0b990a3dafa.jpg",
      user: "Miky Derya",
      action: "mentioned you in",
      target: "Origin UI open graph image",
      timestamp: "2 weeks ago",
      unread: false,
    },
  ]