import { AppSidebar } from "@/components/layout/app-sidebar";
import Notifications from "@/components/layout/Notifications";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "the app",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <div className="px-4 md:px-6 lg:px-8 @container">
            {/* <div className="w-full max-w-7xl mx-auto"> */}
            <div className="w-full mx-auto">
              <header className="flex flex-wrap gap-3 min-h-10 py-4 shrink-0 items-center transition-all ease-linear border-b">
                {/* Left side */}
                <div className="flex flex-1 items-center gap-2">
                  <SidebarTrigger className="-ms-1" />
                  <div className="max-lg:hidden lg:contents">
                    <Separator
                      orientation="vertical"
                      className="me-2 data-[orientation=vertical]:h-4"
                    />
                    <Breadcrumb>
                      <BreadcrumbList>
                        <BreadcrumbItem className="hidden md:block">
                          <BreadcrumbLink href="#">Home</BreadcrumbLink>
                        </BreadcrumbItem>
                        <BreadcrumbSeparator className="hidden md:block" />
                        <BreadcrumbItem>
                          <BreadcrumbPage>Dashboard</BreadcrumbPage>
                        </BreadcrumbItem>
                      </BreadcrumbList>
                    </Breadcrumb>
                  </div>
                </div>
                {/* Right side */}
                <div className="flex gap-3">
                  <Notifications />
                </div>
              </header>
              <div className="overflow-hidden pt-9 pb-5">
                {children}
                {/* <div className="grid auto-rows-min @2xl:grid-cols-2 *:-ms-px *:-mt-px -m-px">
                  {children}
                </div> */}
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </>

  );
}
